// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt6qDkmzuBNzKmm_A7P_XIcWApvjZCEEo',
    appId: '1:397940334764:web:8679ac4d2a13fc68c17f09',
    messagingSenderId: '397940334764',
    projectId: 'bear-4fbd5',
    authDomain: 'bear-4fbd5.firebaseapp.com',
    storageBucket: 'bear-4fbd5.appspot.com',
    measurementId: 'G-E5G6PKRNSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3ZP37QiAULpiRdyAgbLpbcN_ttqvYnuA',
    appId: '1:397940334764:android:464554f47e6fc264c17f09',
    messagingSenderId: '397940334764',
    projectId: 'bear-4fbd5',
    storageBucket: 'bear-4fbd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfXTtbFTW9hBQ3QtCoYw6Iok4GJkzZwEA',
    appId: '1:397940334764:ios:ab36ebb7f5aa2266c17f09',
    messagingSenderId: '397940334764',
    projectId: 'bear-4fbd5',
    storageBucket: 'bear-4fbd5.appspot.com',
    iosBundleId: 'com.example.bear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfXTtbFTW9hBQ3QtCoYw6Iok4GJkzZwEA',
    appId: '1:397940334764:ios:ab36ebb7f5aa2266c17f09',
    messagingSenderId: '397940334764',
    projectId: 'bear-4fbd5',
    storageBucket: 'bear-4fbd5.appspot.com',
    iosBundleId: 'com.example.bear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt6qDkmzuBNzKmm_A7P_XIcWApvjZCEEo',
    appId: '1:397940334764:web:acb04c92500a1094c17f09',
    messagingSenderId: '397940334764',
    projectId: 'bear-4fbd5',
    authDomain: 'bear-4fbd5.firebaseapp.com',
    storageBucket: 'bear-4fbd5.appspot.com',
    measurementId: 'G-HE651FX7FS',
  );
}
